clear
FigWin = figure('Position',[50 50 1280 720],...
   'Name','Fingerprint Recognition System',...
   'NumberTitle','off',...
   'Color',"#FFFFFF");
% Color reference - White: "#FFFFFF"

AxesHandle1 = axes('Position',[0.2 0.15 0.35 0.7],...
   'Box','on');
AxesHandle2 = axes('Position',[0.6 0.15 0.35 0.7],...
   'Box','on');

BackColor = get(gcf,'Color');

FrameBox = uicontrol(FigWin,...
   'Units','normalized', ...
   'Style','frame',...
   'BackgroundColor',"#FFFFFF",...
   'ForegroundColor',"#FFFFFF",...
	'Position',[0 0 0.15 1]);

%create static text.
Text2 = uicontrol(FigWin,...
   'Style','text',...
   'Units','normalized', ...
   'Position',[-0.005 0.95 1 0.05],...
   'FontSize',15,...
   'BackgroundColor',"#FFFFFF",...
   'HorizontalAlignment','right', ...
   'String','Fingerprint Recognition - 99050056');


Text2 = uicontrol(FigWin,...
   'Style','text',...
   'Units','normalized', ...
   'Position',[-0.005 0 1 0.05],...
   'FontSize',15,...
   'BackgroundColor',"#FFFFFF",...
   'HorizontalAlignment','right', ...
   'String','Fingerprint Verification - 99050056');

w=16;
textLoad='Loaded Fingerprint Image';
h=uicontrol(FigWin,...
   'Style','pushbutton',...
   'Position',[20,650,160,40],...
   'String','Load Image',...
   'Callback',...
   ['image1=loadimage;'...
    'subplot(AxesHandle1);'...
    'imagesc(image1);'...
    'title(textLoad);'...
	 'colormap(gray);']);

text_eq='Enhancement by histogram Equalization';
h=uicontrol(FigWin,...
   'Style','pushbutton',...
   'Position',[20,600,160,40],...
   'String','Hist-Equalization',...
   'Callback',...
   ['subplot(AxesHandle2);image1=histeq(uint8(image1));imagesc(image1);title(text_eq);']);

text='Please input the FFT factor(0~1)';
text_fft='Enhancement by FFT';
h=uicontrol(FigWin,...
   'Style','pushbutton',...
   'Position',[20,550,160,40],...
   'String','FFT',...
   'Callback',...
   ['W=inputdlg(text);W=str2double(char(W));'...
    'subplot(AxesHandle1);image1=fftenhance(image1,W);imagesc(image1);title(text_fft);']);

text21='Adaptive Binarization after FFT';
h=uicontrol(FigWin,...
   'Style','pushbutton',...
   'Position',[20,500,160,40],...
   'String','Binarization',...
   'Callback',...
   [%'W=inputdlg(text);W=str2num(char(W));'...
      'subplot(AxesHandle1);'...
      'image1=adaptiveThres(double(image1),32);title(text21);']);

text_filterArea='Orientation Flow Estimate';
h=uicontrol(FigWin,...
   'Style','pushbutton',...
	'Position',[20,450,160,40],...   
	'String','Direction Mapping',...
	'Callback',...
   ['subplot(AxesHandle2);[o1Bound,o1Area]=direction(image1,16);title(text_filterArea);']);

text_ROI='Region Of Interest(ROI)';
h=uicontrol(FigWin,...
   'Style','pushbutton',...
	'Position',[20,400,160,40],...   
	'String','ROI Area',...
	'Callback',...
   ['subplot(AxesHandle2);[o2,o1Bound,o1Area]=drawROI(image1,o1Bound,o1Area);title(text_ROI);']);

text31='Thinned-ridge map';
h=uicontrol(FigWin,...
   'Style','pushbutton',...
   'Position',[20,350,160,40],...
   'String','Thinning',...
   'Callback',...
   ['subplot(AxesHandle2);o1=im2double(bwmorph(o2,''thin'',Inf));imagesc(o1,[0,1]);title(text31);']);

text41='Remove H breaks';
h=uicontrol(FigWin,...
   'Style','pushbutton',...
   'Position',[20,300,160,40],...
   'String','Remove H breaks',...
	'Callback',...
   ['subplot(AxesHandle2);o1=im2double(bwmorph(o1,''clean''));o1=im2double(bwmorph(o1,''hbreak''));imagesc(o1,[0,1]);title(text41);']);


textn1='remove spike';
h=uicontrol(FigWin,...
   'Style','pushbutton',...
   'Position',[20,250,160,40],...
   'String','Remove Spike',...
   'Callback',...
   ['subplot(AxesHandle2);o1=im2double(bwmorph(o1,''spur''));imagesc(o1,[0,1]);title(textn1);']);

%% locate minutia and show all those minutia
text51='Minutia';
h=uicontrol(FigWin,...
   'Style','pushbutton',...
	'Position',[20,200,160,40],...   
	'String','Extract Minutia',...
	'Callback',...
   ['[end_list1,branch_list1,ridgeMap1,edgeWidth]=mark_minutia(o1,o1Bound,o1Area,w);'...
	'subplot(AxesHandle2);show_minutia(o1,end_list1,branch_list1);title(text51);']);

%Process for removing spurious minutia
text61='Remove spurious minutia';
h=uicontrol(FigWin,...
   'Style','pushbutton',...
	'Position',[20,150,160,40],...
	'String','Real Minutiae',...
   'Callback',...
   ['[pathMap1,real_end1,real_branch1]=remove_spurious_Minutia(o1,end_list1,branch_list1,o1Area,ridgeMap1,edgeWidth);'...
   'subplot(AxesHandle1);show_minutia(o1,real_end1,real_branch1);title(text61);']);

%save template file, including the minutia position,direction,and ridge information
textSaveName='file name';
h=uicontrol(FigWin,...
   'Style','pushbutton',...
	'Position',[20,100,160,40],...
	'String','Save File',...
   'Callback',...
   ['W=inputdlg(textSaveName);W=char(W);'...
    'save(W,''real_end1'',''pathMap1'',''-ASCII'');']);

%invoke template file loader and do matching
h=uicontrol('Style','pushbutton',...
   'String','Match Fingerprints',...
	'Position',[20,50,160,40],...
	'Callback',...
   ['finger1=fingerTemplateRead;'...
    'finger2=fingerTemplateRead;'...
    'percent_match=match_end(finger1,finger2,10);']);
